name: 'DiffMasterFlex'
author: 'selfagency'
description: 'Get a list of files that differ between the specified commit and Git ref'
branding:
  icon: 'layers'
  color: 'blue'
inputs:
  sha:
    description: 'SHA against which to diff'
    required: false
  ref:
    description: 'Git ref against which to diff'
    required: false
outputs:
  changed:
    description: 'Whether there were any changes'
  diff:
    description: 'List of changed files'
runs:
  using: 'node20'
  main: 'dist/index.cjs'
